### ISSUE TITLE
Google Regional Language text is not covert into image 

### ISSUE THREAD

**Issue by prataprockerss** [steebchen/text-to-picture#1]
I am taking sample  text (**मैं आपका आभारी हूँ**) from [Google Input](https://www.google.co.in/inputtools/try/) which is not rendering in image. 

## My Code 
```javascript
let result = await textToPicture.convert({
	text: 'मैं आपका आभारी हूँ',
	source: {
		width: 1200,
		height: 920,
		background: 0xFF0000FF
	},
	size: 32,
	quality: 50,
	color: 'white',
	ext: 'jpeg',
});
let str = await result.getBase64();
```

### If anyhow this is possible please let me know

**Comment by steebchen** [comment]
This project uses [oliver-moran/jimp](https://github.com/oliver-moran/jimp) for image manipulation; please try to use this module and check if your text works there. Feel free to re-open if it works using jimp but does not using text-to-picture. If it does not work with jimp either, please open an issue in their repository.
